name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSENAME }}
          password: ${{ secrets.DOCKERTOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vincdelta/discordbot:dev
          
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: 1.0.0
        release_name: Andromeda
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: https://hub.docker.com/layers/241948829/vincdelta/discordbot/dev/images/sha256-58a50e76a86e4c59d7195c3d68d61cb8cc9734d9a3ad7e57da9566089cf57592?context=repo
        asset_name: MAPBot - Dev
        asset_content_type: web/uri

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
