name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSENAME }}
          password: ${{ secrets.DOCKERTOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vincdelta/discordbot:dev

  test:
      
      needs: build
      runs-on: ubuntu-latest
  
      steps:
        - name: rebuilding DO App
          run: | 
            curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -d '{"force_build": true}' https://api.digitalocean.com/v2/apps/${{ secrets.DIGITALOCEAN_APP_ID_DEV}}/deployments
