name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: tagging the dev container image
          uses: docker/tag-action@v2
          with:
            image: vincdelta/discordbot:dev
            tag: vincdelta/discordbot:latest
